### ISSUE TITLE
console.log Aussgabe von systemInfo.js in der Dateiverwaltung

### ISSUE THREAD

**Issue by math-GH** [eikona-media/contao-system-information#1]
In der Dateiverwaltung wirft systemInfo.js eine console.log-Meldung aus.

![grafik](https://user-images.githubusercontent.com/1645099/104818230-99f67700-5826-11eb-8d5e-2a7e3d5cf7db.png)

**Comment by rabauss** [comment]
The problem should be solved with the latest version. We now only load the assets on the system info route!
